name: Build

on: push

jobs:
    build:
        runs-on: x64
        steps:
            - uses: actions/checkout@main
            - name: Build, Analyse
              uses: actions-rs/toolchain@v1.0.7
              with:
                toolchain: stable
            - run: rustup component add clippy
            - run: rustup component add rustfmt
            - run: cargo build
            - run: cargo lint
            - run: cargo analyse